graph LR
  AgentMiniTerminal_invoke["AgentMiniTerminal_invoke"]
  WatchTranscript_IPC["WatchTranscript_IPC"]
  TranscriptWatcher_watch["TranscriptWatcher_watch"]
  DiscoveryLoop["DiscoveryLoop"]
  DiscoverSession["DiscoverSession"]
  DiscoverByMtime["DiscoverByMtime"]
  PopulateEntryRecheck["PopulateEntryRecheck"]
  TranscriptHandle["TranscriptHandle"]
  AppendNormalizedTurn["AppendNormalizedTurn"]
  RotateIfNeeded["RotateIfNeeded"]
  ScanArchiveIndices["ScanArchiveIndices"]
  LoadActive["LoadActive"]
  LoadLastArchive["LoadLastArchive"]
  ListArchives["ListArchives"]
  LoadSnapshot["LoadSnapshot"]
  HasContextsBreadcrumb["HasContextsBreadcrumb"]
  StoreBreadcrumb["StoreBreadcrumb"]
  ProtocolText["ProtocolText"]
  PeerContextPanel["PeerContextPanel"]
  AgentMiniTerminal_invoke --> WatchTranscript_IPC
  WatchTranscript_IPC --> TranscriptWatcher_watch
  TranscriptWatcher_watch --> DiscoveryLoop
  DiscoveryLoop --> DiscoverSession
  DiscoverSession --> DiscoverByMtime
  DiscoverByMtime --> PopulateEntryRecheck
  PopulateEntryRecheck --> TranscriptHandle
  TranscriptHandle --> AppendNormalizedTurn
  TranscriptHandle --> RotateIfNeeded
  TranscriptHandle --> ScanArchiveIndices
  AppendNormalizedTurn --> LoadActive
  AppendNormalizedTurn --> HasContextsBreadcrumb
  AppendNormalizedTurn --> StoreBreadcrumb
  AppendNormalizedTurn --> ProtocolText
  RotateIfNeeded --> LoadLastArchive
  ScanArchiveIndices --> ListArchives
  LoadActive --> LoadSnapshot
  LoadLastArchive --> LoadSnapshot
  ListArchives --> LoadSnapshot
  LoadSnapshot --> PeerContextPanel
