//! Phase 5 interface skeleton for the browser-drawer feature.
//! Emitted by codebase-planner on 2026-05-17.
//!
//! Defines a `BrowserCommands` trait whose method signatures capture
//! the Tauri command surface for the built-in browser. Implementation
//! (downstream) wraps each trait method in a `#[tauri::command]`
//! free function — the macro doesn't expand on trait methods, so the
//! trait here is design-document-shaped, not directly usable as an
//! invoke target.
//!
//! Cross-reference (Phase-3 Round-2 G3): if you change the ALLOW /
//! FILTER / DENY matrix in `validate_browser_url` below, ALSO update
//! `src/lib/urlScheme.ts::classifyScheme`.
//!
//! Implementation prerequisite (Phase-3 Round-1 P0 / Phase 2.5 #1
//! correction): `src-tauri/Cargo.toml` must add `"unstable"` to the
//! `tauri` features list. `Window::add_child` is gated by
//! `#[cfg(all(desktop, feature = "unstable"))]` per `tauri-2.10.3/
//! src/window/mod.rs:1052`.

use serde::{Deserialize, Serialize};

/// CSS / logical pixel rectangle shared with the frontend `Rect`
/// type. Maps to `tauri_runtime::dpi::Rect` at the OS-layer.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct Rect {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

/// Partial-update patch for the `set_browser_settings` command.
/// Mirrors the frontend `BrowserSettingsPatch`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct BrowserSettingsPatch {
    pub browser_drawer_width: Option<u32>,
    pub browser_last_url: Option<String>,
}

/// The browser-drawer's Tauri command surface (9 commands).
///
/// Each method below specifies the contract that the downstream
/// `#[tauri::command]` wrapper must honor. The wrappers are
/// generated by Phase-6+ implementation; this trait is the
/// reviewable design surface.
///
/// **Cross-reference (Phase-3 Round-2 / Phase-5 Round-1)**: if you
/// change the `BrowserSettingsPatch` shape above, ALSO update
/// `src/types/browser.ts::BrowserSettingsPatch` AND the frontend
/// `BrowserIpc::setBrowserSettings` docstring. The manual-mirror
/// convention is the cheapest cross-language type-sync mechanism
/// for a 2-field patch.
#[allow(dead_code)]
pub trait BrowserCommands {
    /// **Responsibility:** Validate the URL, atomically reserve the
    /// `BrowserSlot::Creating` middle state, build the child webview
    /// via `Window::add_child(...)`, install on_page_load /
    /// on_document_title_changed / on_navigation callbacks, then
    /// `CreateGuard::finalize` to transition Creating → Ready.
    ///
    /// **Pipeline-position:** `useBrowserLifecycle.createOnOpen` →
    /// THIS → `BrowserStateOps::try_reserve_for_create` →
    /// `Window::add_child` → `CreateGuard::finalize`.
    ///
    /// **Inputs:**
    /// - `url`: `String` — initial URL. Must pass
    ///   `validate_browser_url` (ALLOW http/https/about:blank).
    /// - `rect`: `Rect` — initial OS-layer position+size in logical
    ///   pixels (Tauri 2 handles DPR translation).
    ///
    /// **Outputs:** `Result<(), String>` — Ok on Creating → Ready
    /// transition. Err on URL validation failure or slot-not-Empty.
    ///
    /// **Side-effects:** Creates one OS-layer webview surface;
    /// installs three Rust-side callbacks (page_load, title_changed,
    /// navigation); transitions BrowserSlot Empty → Creating →
    /// Ready(w) atomically.
    ///
    /// **Preconditions:** `BrowserSlot` is `Empty`. The `unstable`
    /// Tauri feature is enabled. The main window's webview label is
    /// `"main"` (the trusted-app webview from Phase 2.5 L4).
    ///
    /// **Postconditions:** On Ok: `BrowserSlot::Ready(webview)`,
    /// the webview begins async-loading `url`, and one
    /// `browser-loading` event is queued. On Err: slot is back to
    /// `Empty` (CreateGuard rolled back on drop).
    ///
    /// **Failure-modes:**
    /// - `Err("browser webview already exists")` — slot was
    ///   `Creating` or `Ready` at reservation time.
    /// - `Err("filter: ...")` / `Err("deny: ...")` — URL fails
    ///   `validate_browser_url`.
    /// - `Err("invalid URL: ...")` — `url::Url::parse` failure.
    /// - `Err("Window::add_child failed: ...")` — Tauri layer
    ///   error.
    ///
    /// **Collaborators:** `validate_browser_url`,
    /// `BrowserStateOps::try_reserve_for_create`, `Window::add_child`,
    /// `WebviewBuilder::on_page_load` /
    /// `on_document_title_changed` / `on_navigation`,
    /// `CreateGuard::finalize`.
    fn create_browser_webview(url: String, rect: Rect) -> Result<(), String>;

    /// **Responsibility:** Update the OS-layer webview's bounds,
    /// with a Rust-side dedup against `last_bounds` to skip no-op
    /// rect calls during rAF bursts.
    ///
    /// **Pipeline-position:** `useBrowserBounds.syncBounds` (rAF-
    /// debounced) → THIS → `last_bounds` Mutex check → (if changed)
    /// `BrowserStateOps::clone_webview` → `Webview::set_bounds`.
    ///
    /// **Inputs:**
    /// - `rect`: `Rect` — target bounds (logical pixels).
    ///
    /// **Outputs:** `Result<(), String>`.
    ///
    /// **Side-effects:** On dedup miss: moves/resizes the OS-layer
    /// webview surface and updates the `last_bounds` cache. On
    /// dedup hit: no-op.
    ///
    /// **Preconditions:** `BrowserSlot` is `Ready` (otherwise the
    /// command returns `Err("browser webview not created")` without
    /// touching `last_bounds`).
    ///
    /// **Postconditions:** On success: webview's logical rect ==
    /// `rect`; `last_bounds` == `Some(rect)`. Lock-order: acquire
    /// `last_bounds` BEFORE `slot` for the dedup-check; never hold
    /// both simultaneously.
    ///
    /// **Failure-modes:**
    /// - `Err("browser webview not created")` — slot not Ready.
    /// - `Err("set_bounds failed: ...")` — Tauri layer error.
    ///
    /// **Collaborators:** `BrowserStateOps::clone_webview`,
    /// `Webview::set_bounds`, `last_bounds` Mutex.
    fn set_browser_webview_bounds(rect: Rect) -> Result<(), String>;

    /// **Responsibility:** Navigate the browser webview to a new
    /// URL, re-validating the URL Rust-side (defense-in-depth
    /// beyond the frontend `classifyScheme` check).
    ///
    /// **Pipeline-position:** `AddressBar.handleSubmit` (after
    /// classifyScheme="allow") → THIS → `validate_browser_url` →
    /// `BrowserStateOps::clone_webview` → `Webview::navigate`.
    ///
    /// **Inputs:**
    /// - `url`: `String` — frontend-validated, Rust-re-validated.
    ///
    /// **Outputs:** `Result<(), String>` — Ok when the navigate
    /// dispatch returns (NOT when the page finishes loading; that
    /// is signaled by the `browser-loaded` event back-channel).
    ///
    /// **Side-effects:** Triggers webview navigation; network I/O
    /// begins async; webview history stack extends by one entry.
    ///
    /// **Preconditions:** `BrowserSlot` is `Ready`.
    ///
    /// **Postconditions:** Webview begins loading `url`. The
    /// `browser-loading` event fires within ms via the
    /// `on_page_load` callback.
    ///
    /// **Failure-modes:**
    /// - `Err("filter: ...")` / `Err("deny: ...")` —
    ///   `validate_browser_url` rejects.
    /// - `Err("browser webview not created")` — slot not Ready.
    /// - `Err("invalid URL: ...")` — parse failure.
    /// - `Err("navigate failed: ...")` — Tauri layer error.
    ///
    /// **Collaborators:** `validate_browser_url`,
    /// `BrowserStateOps::clone_webview`, `Webview::navigate`.
    fn navigate_browser(url: String) -> Result<(), String>;

    /// **Responsibility:** Fire-and-forget JS `eval` of
    /// `"window.history.back()"` inside the browser webview.
    ///
    /// **Pipeline-position:** `NavControls` back-button → THIS →
    /// `BrowserStateOps::clone_webview` → `Webview::eval`. No
    /// native Rust API for history navigation; eval is the
    /// canonical workaround.
    ///
    /// **Inputs:** None.
    ///
    /// **Outputs:** `Result<(), String>` — Ok when the eval is
    /// dispatched (NOT when the navigation completes; eval is
    /// fire-and-forget per Tauri 2).
    ///
    /// **Side-effects:** May trigger navigation in the webview if
    /// history has prior entries; emits `browser-loading` /
    /// `browser-loaded` on the resulting page load.
    ///
    /// **Preconditions:** `BrowserSlot` is `Ready`.
    ///
    /// **Postconditions:** A JS eval has been queued. At history
    /// boundary, the eval is a no-op in the webview (no error).
    ///
    /// **Failure-modes:**
    /// - `Err("browser webview not created")` — slot not Ready.
    /// - `Err("eval failed: ...")` — Tauri layer error (rare).
    ///
    /// **Collaborators:** `BrowserStateOps::clone_webview`,
    /// `Webview::eval`.
    fn browser_go_back() -> Result<(), String>;

    /// **Responsibility:** Fire-and-forget JS `eval` of
    /// `"window.history.forward()"` inside the browser webview.
    ///
    /// **Pipeline-position:** Same shape as `browser_go_back`.
    ///
    /// **Inputs:** None.
    /// **Outputs:** Same shape as back.
    /// **Side-effects:** Same as back.
    /// **Preconditions:** `BrowserSlot` is `Ready`.
    /// **Postconditions:** Same as back.
    /// **Failure-modes:** Same as back.
    /// **Collaborators:** Same as back.
    fn browser_go_forward() -> Result<(), String>;

    /// **Responsibility:** Reload the current page in the browser
    /// webview via the native `Webview::reload` API.
    ///
    /// **Pipeline-position:** `NavControls` reload-button → THIS →
    /// `BrowserStateOps::clone_webview` → `Webview::reload`.
    ///
    /// **Inputs:** None.
    ///
    /// **Outputs:** `Result<(), String>`.
    ///
    /// **Side-effects:** Triggers a fresh GET to the current URL.
    /// Network I/O resumes; `browser-loading` event fires.
    ///
    /// **Preconditions:** `BrowserSlot` is `Ready`.
    ///
    /// **Postconditions:** Webview begins reloading. Loading state
    /// re-asserts via the event back-channel.
    ///
    /// **Failure-modes:**
    /// - `Err("browser webview not created")` — slot not Ready.
    /// - `Err("reload failed: ...")` — Tauri layer error.
    ///
    /// **Collaborators:** `BrowserStateOps::clone_webview`,
    /// `Webview::reload`.
    fn browser_reload() -> Result<(), String>;

    /// **Responsibility:** Fire-and-forget JS `eval` of
    /// `"window.stop()"` inside the browser webview, aborting any
    /// in-flight page load.
    ///
    /// **Pipeline-position:** `NavControls` stop-button → THIS →
    /// `BrowserStateOps::clone_webview` → `Webview::eval`.
    ///
    /// **Inputs:** None.
    ///
    /// **Outputs:** `Result<(), String>` — fire-and-forget shape.
    ///
    /// **Side-effects:** Aborts current page load; webview may
    /// remain in partially-rendered state. `browser-loaded` event
    /// does NOT fire for the aborted load.
    ///
    /// **Preconditions:** `BrowserSlot` is `Ready`.
    ///
    /// **Postconditions:** Eval dispatched; if no load in progress,
    /// the eval is a no-op.
    ///
    /// **Failure-modes:**
    /// - `Err("browser webview not created")` — slot not Ready.
    /// - `Err("eval failed: ...")` — Tauri layer error.
    ///
    /// **Collaborators:** `BrowserStateOps::clone_webview`,
    /// `Webview::eval`.
    fn browser_stop() -> Result<(), String>;

    /// **Responsibility:** Public IPC wrapper that delegates to
    /// `destroy_browser_webview_impl` (a `pub(crate)` helper shared
    /// with the `RunEvent::Exit` handler). The two-caller split per
    /// Phase-2 L3 resolution: `#[tauri::command]` macros don't
    /// expand on functions callable from `RunEvent::Exit` closures,
    /// so the helper is the actual implementation.
    ///
    /// **Pipeline-position:** `useBrowserLifecycle.destroyOnClose`
    /// → THIS → `destroy_browser_webview_impl` →
    /// `BrowserStateOps::take_webview` → `Webview::close`.
    ///
    /// **Inputs:** None.
    ///
    /// **Outputs:** `Result<(), String>` — Ok on successful
    /// Ready → Empty transition OR Ok on already-Empty (idempotent).
    ///
    /// **Side-effects:** Destroys the OS-layer webview surface;
    /// `BrowserSlot` becomes `Empty`; cookies persist via the
    /// engine profile (Phase 1 Q6).
    ///
    /// **Preconditions:** None — calling on `Empty` is a no-op.
    ///
    /// **Postconditions:** `BrowserSlot::Empty`. No further
    /// nav-events fire from this instance.
    ///
    /// **Failure-modes:**
    /// - `Err("Webview::close failed: ...")` — Tauri layer error
    ///   (rare).
    /// - Already-Empty returns Ok (idempotent).
    ///
    /// **Collaborators:** `destroy_browser_webview_impl` (helper),
    /// `BrowserStateOps::take_webview`, `Webview::close`.
    fn destroy_browser_webview() -> Result<(), String>;

    /// **Responsibility:** Partial-update the persisted settings.json
    /// with the browser-drawer fields (`browser_drawer_width`,
    /// `browser_last_url`), serialized against the existing
    /// `set_settings` writer via `AppState.settings_io_lock`.
    ///
    /// Phase-3 Round-2 3-way convergent fix (claude3 G1 / codex2 P1
    /// / codex3 #2): partial-update command exists because
    /// `set_settings` rewrites the whole `Settings` struct, which
    /// races with concurrent settings writers (UpdateBanner etc.)
    /// and would lose updates without a serialization lock.
    ///
    /// Phase-5 Round-1 cohort fix: this method was missing from the
    /// Rust skeleton in revision 1 even though the TS counterpart
    /// `BrowserIpc::setBrowserSettings` existed — 3-way convergent
    /// (claude2 S1 / codex2 P1 / codex3 #1). Added in revision 2.
    ///
    /// **Pipeline-position:** `useBrowserLifecycle.persistSettings`
    /// (debounced) → THIS → acquire `AppState.settings_io_lock` →
    /// read `settings.json` → merge patch fields → write back →
    /// release lock.
    ///
    /// **Inputs:**
    /// - `patch`: `BrowserSettingsPatch` — at least one of
    ///   `browser_drawer_width` (Option<u32>) or `browser_last_url`
    ///   (Option<String>) should be `Some`. `None` fields are NOT
    ///   written (preserves the existing value on disk).
    ///
    /// **Outputs:** `Result<(), String>` — Ok after the file write
    /// completes and the lock is released.
    ///
    /// **Side-effects:** One read + one write of `app_config_dir/
    /// settings.json`. Holds `AppState.settings_io_lock` for the
    /// full read-modify-write cycle. Disk I/O.
    ///
    /// **Preconditions:** `AppState.settings_io_lock` is registered
    /// in the Tauri app's managed state. NOTE: this Phase-5 skeleton
    /// only documents the requirement — implementation must extend
    /// `AppState` with the `settings_io_lock: Mutex<()>` field per
    /// `.planner-state.json::implementation_prerequisites::
    /// state_types_to_materialize`.
    ///
    /// **Postconditions:** The two browser fields in settings.json
    /// reflect the patch values (where `Some`); other fields
    /// (`auto_check_updates`, `last_skipped_version`) are preserved
    /// unchanged. The file is atomically replaced (write-temp-and-
    /// rename is the recommended downstream pattern; Phase-3
    /// doesn't commit to it).
    ///
    /// **Failure-modes:**
    /// - `Err("read settings.json failed: ...")` — file missing,
    ///   permission denied, malformed JSON.
    /// - `Err("write settings.json failed: ...")` — disk full,
    ///   permission denied.
    /// - Lock acquisition is unconditional (`Mutex<()>::lock` returns
    ///   `LockResult` but `Mutex<()>` is poison-clean by construction).
    ///
    /// **Collaborators:** `AppState.settings_io_lock`,
    /// `commands::settings::Settings` struct, `std::fs::read_to_
    /// string`, `std::fs::write`, `serde_json::from_str` /
    /// `to_string_pretty`.
    fn set_browser_settings(patch: BrowserSettingsPatch) -> Result<(), String>;
}

/// Rust-side URL validator — defense-in-depth mirror of
/// `src/lib/urlScheme.ts::classifyScheme`. Implementation
/// (downstream) adds the `pub fn` body; this skeleton documents
/// the contract.
///
/// Phase-5 Note: this is a free function, not a trait method, so
/// per the Rust skeleton convention it's specified by docstring +
/// type alias rather than a `fn ... ;` declaration (Rust requires
/// bodies on free functions). The implementation phase resolves
/// to: `pub(crate) fn validate_browser_url(input: &str) ->
/// Result<url::Url, String>` (the `url` crate is a transitive
/// Tauri 2 dep; add to direct deps at implementation time).
///
/// **Responsibility:** Parse `input` and classify per the Phase-1
/// Q5 ALLOW (`http:`/`https:`/`about:blank`) / FILTER (`javascript:`/
/// `tauri:`/`tauri-localhost:`/`data:`) / DENY (`file:`) policy.
/// Returns the parsed `Url` on ALLOW; `Err(reason)` on FILTER/DENY.
///
/// **Pipeline-position:** any callsite needing URL gating → THIS →
/// (on Ok) `Webview::navigate` or `Window::add_child` continues; (on
/// Err) caller returns the Err string up the stack.
///
/// **Inputs:** `input: &str` — raw URL string from a frontend
/// command or an `on_navigation` callback `&Url`. Tolerant of
/// leading/trailing whitespace, mixed-case scheme, malformed inputs.
///
/// **Outputs:** `Result<url::Url, String>` — Ok parsed URL; Err
/// includes the action label (`"filter: javascript: URLs blocked"`).
///
/// **Side-effects:** None. Pure parsing + matching.
/// **Preconditions:** None. Tolerant of any input.
/// **Postconditions:** Output is deterministic for the same input.
/// **Failure-modes:** Returns `Err`; never panics.
/// **Collaborators:** `url::Url::parse`.
///
/// **Cross-reference requirement:** If you change the ALLOW / FILTER
/// / DENY matrix in the implementation, ALSO update
/// `src/lib/urlScheme.ts::classifyScheme`.
#[allow(dead_code)]
pub type ValidateBrowserUrlSignature = fn(input: &str) -> Result<tauri::Url, String>;

// Additional skeleton-only types/traits that implementation
// phase will materialize:
//
// - BrowserSlot { Empty, Creating, Ready(Webview<R>) } enum on the
//   Rust side, mirroring the slot-reservation invariant from
//   Phase-3 Round-2 codex3 #1.
// - BrowserWebviewState<R> struct with `slot: Mutex<BrowserSlot<R>>`
//   and `last_bounds: Mutex<Option<Rect>>` fields.
// - BrowserStateOps trait with `clone_webview`, `take_webview`,
//   `try_reserve_for_create` method signatures.
// - CreateGuard<'a, R> RAII guard with `finalize(Webview<R>)`.
// - AppState::settings_io_lock: Mutex<()> field for serializing
//   `set_settings` and `set_browser_settings` (Phase-3 Round-2
//   3-way convergent fix).
//
// These are deliberately omitted from this skeleton file because
// they reference `tauri::Webview<R>` (which requires `R: Runtime`
// generic plumbing). The interface skeleton documents the IPC
// contract surface (the trait + shared shapes above); state-cell
// primitives are an implementation detail of the contract.
