//! FSD wire-format schemas.
//!
//! These types mirror the TypeScript `src/types/fsd.ts` definitions; the two
//! must produce identical verdicts on the same input (per plan v5 §2 two-layer
//! validation paragraph). A future paired fuzzer asserts this invariant.
//!
//! ## Protocol grammar (plan v5 §3)
//!
//! Leaders emit single-line JSON commands prefixed with `##FSD `:
//! ```text
//! ##FSD {"v":1,"cmd_id":"...","sn":"...","rn":"...","run_id":"...",
//!        "type":"plan","goal":"...","success_criteria":[...],"max_turns":4}
//! ```
//!
//! Verbs: `plan`, `dispatch`, `done`, `blocked`. All four ship in Phase 1.

use serde::{Deserialize, Serialize};

/// Schema version. Increment for breaking changes; reject unknown versions
/// with a one-time warning per session.
pub(crate) const SCHEMA_VERSION: u32 = 1;

/// FSD multiplier tier. Matches the user spec: x1 = 4 assistants, x2 = 8,
/// x3 = 12. Phase 1 ships only `Off` and `Pilot` (single-CLI, single-assistant)
/// per plan v5 §5.1.
///
/// Currently consumed by the frontend `src/types/fsd.ts` mirror only — Rust
/// orchestrator passes tier as `u8` for IPC simplicity. Kept here as the
/// canonical schema documentation.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub(crate) enum FsdTier {
    Off,
    Pilot, // Phase 1 honest label (was x1 in the user spec, but Pilot = 1+1 only)
    X1,    // Phase 2: 1 of each tool (4 assistants)
    X2,    // Phase 2: 2 of each (8)
    X3,    // Phase 3: 3 of each (12)
}

/// Which channel the leader uses to emit commands. Chip surfaces this so the
/// user knows whether MCP is active or prompt-eng is the only path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum EmissionMode {
    /// Stdout `##FSD {json}` lines parsed by `fsdLineTap.ts`.
    PromptLines,
    /// Native MCP tool calls (Claude Code, Codex, etc.).
    McpTools,
    /// Both available; leader picks per emission. Orchestrator dedupes by
    /// `(run_id, cmd_id)` per plan v5 §5.5.
    Both,
    /// Toggle disabled — no path is reliable enough per Phase 0 verdict.
    Unavailable,
}

/// Every leader-emitted command carries these envelope fields.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct FsdEnvelope {
    /// Schema version. Reject if != SCHEMA_VERSION.
    pub v: u32,
    /// Per-command UUID generated by the leader. Orchestrator dedupes —
    /// MCP tool calls and stdout `##FSD` lines share the same `(run_id, cmd_id)`
    /// dedup key (plan v5 §5.5).
    pub cmd_id: String,
    /// 8-hex session nonce. Issued by orchestrator on `fsd_set_tier(>0)`.
    /// Mismatch → §5.2 discriminator (drop or strike-and-remind).
    pub sn: String,
    /// 8-hex run nonce. Issued at the start of each run. Mismatch → §5.2.
    pub rn: String,
    /// UUID per user prompt. Leader emits a fresh one on each `plan`.
    pub run_id: String,
}

/// All four verbs as a tagged union.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub(crate) enum FsdCommand {
    Plan {
        #[serde(flatten)]
        env: FsdEnvelope,
        /// User's prompt verbatim.
        goal: String,
        /// Free-form success criteria the leader will use for self-evaluation.
        #[serde(default)]
        success_criteria: Vec<String>,
        /// Leader-requested cap on turns; clamped server-side to ≤ MAX_TURNS_CEILING.
        #[serde(default = "default_max_turns")]
        max_turns: u32,
    },
    Dispatch {
        #[serde(flatten)]
        env: FsdEnvelope,
        /// 1-indexed turn number within the run.
        turn: u32,
        /// Per-task envelopes. Length capped at MAX_TASKS_PER_DISPATCH server-side.
        tasks: Vec<TaskSpec>,
    },
    Done {
        #[serde(flatten)]
        env: FsdEnvelope,
        /// Final user-visible answer.
        summary: String,
        /// Optional: artifact paths or citations for the user to verify.
        #[serde(default)]
        evidence: Vec<String>,
    },
    Blocked {
        #[serde(flatten)]
        env: FsdEnvelope,
        /// Machine tag, e.g. "roster-empty", "auth-missing", "leader-cant-decide".
        reason: String,
        /// Optional: missing tool/capability name.
        #[serde(default)]
        missing_capability: Option<String>,
        /// Optional: human-readable prompt for the user (Phase 3 re-entry flow).
        #[serde(default)]
        needed_user_input: Option<String>,
        /// `cmd_id` of the last successful action — debugging aid.
        #[serde(default)]
        last_cmd_id: Option<String>,
    },
}

fn default_max_turns() -> u32 {
    crate::fsd::orchestrator::MAX_TURNS_DEFAULT
}

/// One assistant's task within a `dispatch`. The leader authors the prompt;
/// the harness only validates schema and bounds.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct TaskSpec {
    /// Stable per-task ID (`t-<turn>-<a/b/c>`).
    pub task_id: String,
    /// Which CLI to spawn. Phase 1 Pilot accepts only the spike-selected CLI.
    pub tool: String,
    /// 1-indexed instance within the same tool (for x2/x3 multi-instance).
    pub instance_idx: u32,
    /// Free-form role descriptor (no fixed taxonomy in Phase 1).
    pub role_hint: Option<String>,
    /// Tailored prompt for this assistant.
    pub prompt: String,
    /// Optional: paths to context files the assistant should read (typically
    /// previous turn's results).
    #[serde(default)]
    pub context_refs: Vec<String>,
    /// Per-task wallclock cap. Clamped server-side.
    #[serde(default = "default_task_wallclock_ms")]
    pub wallclock_ms_cap: u64,
}

fn default_task_wallclock_ms() -> u64 {
    120_000
}

// ---------------------------------------------------------------------------
// Storage manifests (written to disk under fsd-runs/)
// ---------------------------------------------------------------------------

/// Top-level run manifest at `fsd-runs/<leader>/runs/<run_id>/manifest.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct RunManifest {
    pub run_id: String,
    pub leader_handle: String,
    /// PID of the canvas-terminal process that owns this run. `recover_runs()`
    /// uses this + `is_process_alive` to detect crashes (plan v5 §5.3).
    pub owner_pid: u32,
    /// ISO-8601. Used as the canonical sort key for retention (plan v5 §5.6 /
    /// item K) — NOT filesystem mtime, which recovery rewrites can skew.
    pub started_at: String,
    /// Heartbeat — orchestrator writes every ~10s while run is active.
    /// Recovery marks runs interrupted if `now - last_heartbeat_at > 60s`,
    /// catching orchestrator-task wedge while owning process is alive (R15).
    pub last_heartbeat_at: String,
    pub status: RunStatus,
    /// Active session/run nonces. Captured here so recovery can verify
    /// expectations on a partial run.
    pub session_nonce: String,
    pub run_nonce: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum RunStatus {
    /// In-flight states — `recover_runs()` marks these `Interrupted` if owner
    /// is dead OR heartbeat is stale.
    Running,
    Dispatching,
    AwaitingLeader,
    /// Terminal states — eligible for retention sweep (plan v5 §5.3).
    Done,
    Blocked,
    Cancelled,
    CapTripped,
    Interrupted,
}

impl RunStatus {
    pub fn is_active(self) -> bool {
        matches!(
            self,
            RunStatus::Running | RunStatus::Dispatching | RunStatus::AwaitingLeader
        )
    }

    pub fn is_terminal(self) -> bool {
        !self.is_active()
    }
}

/// Per-task done.json written when an assistant subprocess exits.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct TaskDone {
    pub task_id: String,
    pub run_id: String,
    pub turn: u32,
    pub tool: String,
    pub exit_code: Option<i32>,
    pub wallclock_ms: u64,
    pub stdout_bytes: u64,
    pub stderr_bytes: u64,
    pub stdout_path: String, // relative to fsd-runs/
    pub stderr_path: String,
    pub error: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plan_command_round_trips() {
        let cmd = FsdCommand::Plan {
            env: FsdEnvelope {
                v: 1,
                cmd_id: "abc".into(),
                sn: "a3f1c92e".into(),
                rn: "7b4d8e10".into(),
                run_id: "run-1".into(),
            },
            goal: "list files".into(),
            success_criteria: vec!["all files listed".into()],
            max_turns: 3,
        };
        let json = serde_json::to_string(&cmd).unwrap();
        let parsed: FsdCommand = serde_json::from_str(&json).unwrap();
        match parsed {
            FsdCommand::Plan { env, goal, max_turns, .. } => {
                assert_eq!(env.cmd_id, "abc");
                assert_eq!(goal, "list files");
                assert_eq!(max_turns, 3);
            }
            _ => panic!("wrong variant after round-trip"),
        }
    }

    #[test]
    fn dispatch_with_tasks_round_trips() {
        let json = r#"{
            "v": 1,
            "cmd_id": "c1",
            "sn": "11111111",
            "rn": "22222222",
            "run_id": "r1",
            "type": "dispatch",
            "turn": 1,
            "tasks": [
                {"task_id": "t-1-a", "tool": "claude_code", "instance_idx": 1,
                 "prompt": "review src/lib.rs"}
            ]
        }"#;
        let cmd: FsdCommand = serde_json::from_str(json).unwrap();
        match cmd {
            FsdCommand::Dispatch { tasks, .. } => {
                assert_eq!(tasks.len(), 1);
                assert_eq!(tasks[0].task_id, "t-1-a");
                assert_eq!(tasks[0].wallclock_ms_cap, 120_000); // default
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn blocked_with_optional_fields() {
        let json = r#"{
            "v": 1, "cmd_id": "c1", "sn": "x", "rn": "y", "run_id": "r1",
            "type": "blocked",
            "reason": "auth-missing",
            "missing_capability": "gemini-cli"
        }"#;
        let cmd: FsdCommand = serde_json::from_str(json).unwrap();
        match cmd {
            FsdCommand::Blocked { reason, missing_capability, needed_user_input, .. } => {
                assert_eq!(reason, "auth-missing");
                assert_eq!(missing_capability.as_deref(), Some("gemini-cli"));
                assert_eq!(needed_user_input, None);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn run_status_active_vs_terminal() {
        assert!(RunStatus::Running.is_active());
        assert!(RunStatus::Dispatching.is_active());
        assert!(!RunStatus::Done.is_active());
        assert!(RunStatus::Done.is_terminal());
        assert!(RunStatus::Interrupted.is_terminal());
    }
}
