/**
 * Scoped collab-memory IPC contract — planner-emitted interface skeleton.
 *
 * Cross-boundary contract between the Rust memory commands
 * (`src-tauri/src/commands/memory.rs`) and every TypeScript consumer
 * (collaboratorStore, collaborator commands, peerContext). Each method
 * mirrors one Tauri IPC command after the per-collab-session isolation
 * change: every command gains a `collabSessionId` scope and resolves
 * paths strictly inside `session-<pid>/<collabSessionId>/`.
 *
 * Planner run: collab-isolation-agy-46135-45591-1034 (plan-feature lane).
 * NO IMPLEMENTATION here by contract — bodies are generated by
 * codebase-implementer after the human-confirmed merge marker lands.
 */

/**
 * Result triple for directory listings that must distinguish files from
 * directories without a second stat round-trip. Mirrors the existing
 * `list_directory` convention `[name, isDir, fullPath]`.
 */
export type MemoryFileEntry = string;

/**
 * TS-side facade over the scoped Rust memory IPC commands.
 *
 * Cohesion: all methods read/write the same per-collab-session directory
 * subtree and share one failure domain (the Rust path gate).
 */
export interface ScopedMemoryIpc {
  /**
   * Responsibility: Read one file from THIS collab session's memory subtree.
   * Pipeline-position: ScopedMemoryClient.getMemorySessionDir -> THIS -> AgentHeaderBuilder.prependContextHeader / SlashCommandMemoryOps
   * Inputs:
   *   - collabSessionId: string — non-empty; opaque pane id; sanitized Rust-side by sanitize_collab_session_id (single source of truth); a value that sanitizes to empty is rejected, never silently mapped to the root
   *   - relativePath: string — relative to the SESSION subtree; no `..`, no absolute components (validate_relative_path invariant)
   * Outputs: Promise<string | null> — file content on success; null when the file does not exist (missing-vs-error distinction is load-bearing for context.md probing)
   * Side-effects: None. (read-only; follows symlinks like today's read_memory_file — write/delete reject them)
   * Preconditions: collabSessionId identifies the CALLING pane's session; callers must not pass another pane's id (UI never offers one)
   * Postconditions: no path outside session-<pid>/<collabSessionId>/ was read; idempotent
   * Failure-modes:
   *   - Error("Path traversal ...") — relativePath contained `..`/absolute component
   *   - Error("Invalid collab session id") — id empty after sanitize
   *   - Error("Memory file too large ...") — file exceeds the 10 MB read cap
   *   - Error(io) — stat/read failed for an existing file
   * Collaborators: Rust memory::read_memory_file (scoped); memory::get_memory_session_dir.
   */
  readMemoryFile(collabSessionId: string, relativePath: string): Promise<string | null>;

  /**
   * Responsibility: Write (create/truncate) one file inside THIS collab session's memory subtree.
   * Pipeline-position: SlashCommandMemoryOps (/context set) / appendLog write chain -> THIS -> peer agents' reads
   * Inputs:
   *   - collabSessionId: string — same constraint as readMemoryFile
   *   - relativePath: string — same constraint as readMemoryFile; parent dirs are created inside the session subtree only
   *   - content: string — full replacement content (not append)
   * Outputs: Promise<string> — absolute path of the written file (used for status echoes)
   * Side-effects: creates session dir + parents on first write; truncates existing file; O_NOFOLLOW open
   * Preconditions: caller owns collabSessionId (same rule as readMemoryFile)
   * Postconditions: file exists under session-<pid>/<collabSessionId>/ with exactly `content`; no sibling session dir touched
   * Failure-modes:
   *   - Error("Refusing to write through a symlink") — existing symlink at target
   *   - Error("Path traversal ...") / Error("Invalid collab session id") — gate violations
   *   - Error(io) — create/write/flush failed
   * Collaborators: Rust memory::write_memory_file (scoped); memory::get_memory_session_dir.
   */
  writeMemoryFile(collabSessionId: string, relativePath: string, content: string): Promise<string>;

  /**
   * Responsibility: Atomically replace one file inside THIS collab session's subtree (readers see old or new, never partial).
   * Pipeline-position: dashboard roster sidecar writer (agents-*.json) -> THIS -> dashboard SSE poller reads
   * Inputs:
   *   - collabSessionId: string — same constraint as readMemoryFile
   *   - relativePath: string — same constraint as readMemoryFile
   *   - content: string — full replacement content
   * Outputs: Promise<string> — absolute path of the final file
   * Side-effects: tmp file `.{basename}.{pid}.{nanos}.tmp` in the same session-scoped parent; fsync of tmp; rename over final path
   * Preconditions: caller owns collabSessionId
   * Postconditions: final path holds exactly `content`; tmp file removed on every failure path; visibility-atomic for concurrent readers
   * Failure-modes:
   *   - Error("Refusing to write through a symlink"/"...rename over a symlink") — symlink at final path (pre-write and pre-rename TOCTOU re-check)
   *   - Error("Refusing to write through symlinked path component ...") — planted symlink on the relative path walk
   *   - Error("Path traversal ...") / Error("Invalid collab session id") — gate violations
   *   - Error(io) — tmp create/write/fsync/rename failed
   * Collaborators: Rust memory::write_memory_file_atomic (scoped); memory::get_memory_session_dir.
   */
  writeMemoryFileAtomic(collabSessionId: string, relativePath: string, content: string): Promise<string>;

  /**
   * Responsibility: Delete one regular file from THIS collab session's subtree and prune empty parents up to the session root.
   * Pipeline-position: TaskCompletionScanner (orphan done.json cleanup) / SlashCommandMemoryOps (/memory delete, /context clear) -> THIS -> (terminal)
   * Inputs:
   *   - collabSessionId: string — same constraint as readMemoryFile
   *   - relativePath: string — same constraint as readMemoryFile
   * Outputs: Promise<boolean> — true if deleted; false if the file did not exist
   * Side-effects: removes the file; removes now-empty parent dirs but never above session-<pid>/<collabSessionId>/
   * Preconditions: caller owns collabSessionId
   * Postconditions: path absent; session root dir itself is never removed by this command; idempotent (second call returns false)
   * Failure-modes:
   *   - Error("Refusing to delete a symlink") — symlink at target
   *   - Error("Cannot delete a directory ...") — target is a directory
   *   - Error("Path traversal ...") / Error("Invalid collab session id") — gate violations
   *   - Error(io) — unlink failed
   * Collaborators: Rust memory::delete_memory_file (scoped); memory::get_memory_session_dir.
   */
  deleteMemoryFile(collabSessionId: string, relativePath: string): Promise<boolean>;

  /**
   * Responsibility: Remove THIS collab session's entire memory subtree and recreate it empty (used by /memory clear and session teardown).
   * Pipeline-position: SlashCommandMemoryOps (/memory clear) / endSession teardown -> THIS -> (terminal)
   * Inputs:
   *   - collabSessionId: string — same constraint as readMemoryFile; scoping is the isolation guarantee: ONLY this session's subtree is affected
   * Outputs: Promise<void> — resolves when the subtree is recreated empty
   * Side-effects: recursive delete of session-<pid>/<collabSessionId>/; mkdir of the same path
   * Preconditions: caller owns collabSessionId; no sibling-session path may be derivable from the input (Rust re-derives the path, never trusts a caller path)
   * Postconditions: session subtree exists and is empty; sibling session subtrees and root-level files are untouched
   * Failure-modes:
   *   - Error("Invalid collab session id") — id empty after sanitize
   *   - Error(io) — remove_dir_all/create_dir_all failed
   * Collaborators: Rust memory::clear_memory_dir (scoped); memory::get_memory_session_dir.
   */
  clearMemoryDir(collabSessionId: string): Promise<void>;

  /**
   * Responsibility: List every file (recursive, relative paths) inside THIS collab session's subtree only.
   * Pipeline-position: SlashCommandMemoryOps (/memory list) / TaskCompletionScanner scan loop -> THIS -> per-file readMemoryFile
   * Inputs:
   *   - collabSessionId: string — same constraint as readMemoryFile
   * Outputs: Promise<MemoryFileEntry[]> — sorted, session-relative paths; NEVER contains entries from sibling sessions or the root level (this is the structural fix for the cross-pane leak)
   * Side-effects: None. (read-only directory walk)
   * Preconditions: caller owns collabSessionId
   * Postconditions: every returned path re-joins under the session subtree; idempotent between mutations
   * Failure-modes:
   *   - Error("Invalid collab session id") — id empty after sanitize
   *   - (missing session dir) — returns [] rather than erroring (fresh session, nothing written yet)
   * Collaborators: Rust memory::list_memory_files (scoped); memory::get_memory_session_dir.
   */
  listMemoryFiles(collabSessionId: string): Promise<MemoryFileEntry[]>;

  /**
   * Responsibility: Report a session file's mtime as Unix epoch milliseconds (grace-period gate for orphan done.json cleanup).
   * Pipeline-position: TaskCompletionScanner.scanForTaskCompletions -> THIS -> deleteMemoryFile (when past grace period)
   * Inputs:
   *   - collabSessionId: string — same constraint as readMemoryFile
   *   - relativePath: string — same constraint as readMemoryFile
   * Outputs: Promise<number> — epoch ms of last modification
   * Side-effects: None. (stat only; follows symlinks, consistent with readMemoryFile)
   * Preconditions: caller owns collabSessionId
   * Postconditions: no state change; monotone non-decreasing between writes for a given file
   * Failure-modes:
   *   - Error("stat <path>: ...") — file missing OR filesystem lacks mtime support (caller treats both as skip, per existing contract)
   *   - Error("Path traversal ...") / Error("Invalid collab session id") — gate violations
   * Collaborators: Rust memory::get_memory_file_mtime (scoped); memory::get_memory_session_dir.
   */
  getMemoryFileMtime(collabSessionId: string, relativePath: string): Promise<number>;
}

/**
 * Session-directory resolution surface consumed by prompt/header builders.
 *
 * Cohesion: both methods derive display/breadcrumb paths from the same
 * scoped session root that ScopedMemoryIpc enforces.
 */
export interface ScopedMemoryClient {
  /**
   * Responsibility: Resolve (and lazily create) the absolute path of THIS collab session's memory subtree for display in injected agent headers.
   * Pipeline-position: sendToAgent/broadcastToAll header assembly -> THIS -> AgentHeaderBuilder.prependContextHeader / buildSlimHeader / buildTaskProtocol grep targets
   * Inputs:
   *   - collabSessionId: string — non-empty pane id; sanitized Rust-side; same value the Rust mirror writer uses so header paths and mirror paths cannot diverge
   * Outputs: Promise<string> — absolute path `~/.cache/canvas-terminal/collab-memory/session-<pid>/<sanitizedId>/` (no trailing slash)
   * Side-effects: creates the session subtree if absent (mkdir -p semantics)
   * Preconditions: called only with the pane's own id (callers thread agent.collabSessionId, never user input)
   * Postconditions: returned path exists; equal for equal ids within one app process (cacheable); every path printed into an agent prompt is a prefix-descendant of it
   * Failure-modes:
   *   - Error("Invalid collab session id") — id empty after sanitize
   *   - Error("Cannot determine home directory") / Error(io) — root resolution or mkdir failed
   * Collaborators: Rust memory::init_memory_dir (scoped variant); ScopedMemoryIpc.* (path base).
   */
  getMemorySessionDir(collabSessionId: string): Promise<string>;
}
