use portable_pty::{Child, MasterPty};
use std::collections::HashMap;
use std::io::Write;
use std::sync::Mutex;
use std::thread::JoinHandle;

pub struct PtySession {
    // Drop order matters: child first, then writer, then reader thread (join), then master last.
    // Rust drops fields in declaration order, but we use an explicit Drop impl for safety.
    pub child: Box<dyn Child + Send + Sync>,
    pub writer: Box<dyn Write + Send>,
    pub reader_thread: Option<JoinHandle<()>>,
    pub master: Box<dyn MasterPty + Send>,
}

impl Drop for PtySession {
    fn drop(&mut self) {
        // 1. Kill child process — causes PTY to send EOF/EIO to reader
        let _ = self.child.kill();
        // 2. Drop writer — closes write end of PTY
        // (writer is dropped automatically after this fn, but we want ordering clarity)
        // 3. Join reader thread — wait for it to finish reading before dropping master
        if let Some(handle) = self.reader_thread.take() {
            let _ = handle.join();
        }
        // 4. master drops automatically last (declared last in struct)
    }
}

pub struct AppState {
    pub sessions: Mutex<HashMap<String, PtySession>>,
    /// Cached shell environment — resolved once via login shell, reused for all PTYs.
    /// None = not yet bootstrapped. Some(map) = ready.
    pub cached_env: Mutex<Option<HashMap<String, String>>>,
    /// Serialization lock for settings.json read-modify-write. Both
    /// `set_settings` (full struct) and `set_browser_settings` (partial)
    /// acquire this during their RMW cycle so concurrent writers can't
    /// lose updates. Phase-3 Round-2 3-way convergent fix.
    pub settings_io_lock: Mutex<()>,
}

impl AppState {
    pub fn new() -> Self {
        Self {
            sessions: Mutex::new(HashMap::new()),
            cached_env: Mutex::new(None),
            settings_io_lock: Mutex::new(()),
        }
    }
}

// ---------------------------------------------------------------------------
// Browser-tabs state (browser-tabs cycle — feature/browser-integration)
// ---------------------------------------------------------------------------

use tauri::{LogicalPosition, LogicalSize, Position, Rect as DpiRect, Runtime, Size, Webview};

/// Tab identifier — UUID string generated by the frontend via
/// `crypto.randomUUID()`. Used both as the map key in `BrowserTabsState`
/// and as the suffix of the Tauri webview label (`browser-tab-<uuid>`).
pub type TabId = String;

/// Per-tab webview slot. Mirrors the prior singleton state machine
/// (Empty → Creating → Ready → Empty) but is now stored in a
/// `HashMap<TabId, BrowserSlot<R>>` so every tab has independent
/// lifecycle and CreateGuard generation tracking.
///
/// `Empty` is documented but not currently inserted into the map —
/// destroyed tabs simply remove the entry. Kept for future explicit
/// pre-create reservation flows.
pub enum BrowserSlot<R: Runtime> {
    #[allow(dead_code)]
    Empty,
    Creating {
        generation: u64,
    },
    Ready {
        // Read by the variant-pattern match in `take_tab` / `clone_tab`
        // even though the field itself is destructured with `..`.
        #[allow(dead_code)]
        generation: u64,
        webview: Webview<R>,
    },
}

/// Wire-format rect used at the IPC boundary. Mirrors `src/types/browser.ts::Rect`.
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Rect {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

impl Rect {
    /// Translate the IPC rect into Tauri's logical-pixel rect used by
    /// `Webview::set_bounds`. Tauri 2 handles DPR internally.
    pub fn to_dpi_rect(self) -> DpiRect {
        DpiRect {
            position: Position::Logical(LogicalPosition { x: self.x, y: self.y }),
            size: Size::Logical(LogicalSize {
                width: self.width,
                height: self.height,
            }),
        }
    }
}

/// Browser-drawer Rust-side state. Two `HashMap`-backed mutexes plus a
/// global monotonic generation counter:
/// - `tabs`: per-tab `BrowserSlot` machine (Empty → Creating → Ready → Empty).
/// - `last_bounds`: per-tab Rect dedup cache for `set_browser_tab_bounds`
///   (per-tab — a singleton cache would thrash on every active-tab switch).
/// - `generation`: shared monotonic counter; each tab's `CreateGuard`
///   captures its slot generation independently.
///
/// Lock-order convention: `last_bounds` BEFORE `tabs`. No command currently
/// locks both simultaneously; documented for future regression prevention.
pub struct BrowserTabsState<R: Runtime> {
    pub tabs: Mutex<HashMap<TabId, BrowserSlot<R>>>,
    pub last_bounds: Mutex<HashMap<TabId, Rect>>,
    pub generation: std::sync::atomic::AtomicU64,
}

impl<R: Runtime> BrowserTabsState<R> {
    pub fn new() -> Self {
        Self {
            tabs: Mutex::new(HashMap::new()),
            last_bounds: Mutex::new(HashMap::new()),
            generation: std::sync::atomic::AtomicU64::new(0),
        }
    }

    /// Deterministic webview label from a tab id. Tauri rejects duplicate
    /// webview labels, so we prefix the UUID with `browser-tab-` so the
    /// shape is stable + searchable in logs.
    pub fn label_for(tab_id: &str) -> String {
        format!("browser-tab-{}", tab_id)
    }

    /// Non-destroy primitive: clone the `Webview<R>` handle out of the
    /// slot if it's `Ready`. Used by per-tab nav commands. Leaves the
    /// slot in `Ready`.
    pub fn clone_tab(&self, tab_id: &str) -> Option<Webview<R>> {
        let tabs = self.tabs.lock().ok()?;
        match tabs.get(tab_id)? {
            BrowserSlot::Ready { webview, .. } => Some(webview.clone()),
            _ => None,
        }
    }

    /// Destroy-only primitive: always transition the slot to `Empty`
    /// (removed from the map entirely), regardless of current state.
    /// - `Ready { webview, .. }` → return `Some(webview)`, entry removed.
    /// - `Creating { .. }` → entry removed; in-flight `finalize` with that
    ///   generation will see the mismatch and close-and-discard the
    ///   webview it was about to publish.
    /// - `Empty` / missing → no-op `None`.
    pub fn take_tab(&self, tab_id: &str) -> Option<Webview<R>> {
        let mut tabs = self.tabs.lock().ok()?;
        match tabs.remove(tab_id)? {
            BrowserSlot::Ready { webview, .. } => Some(webview),
            BrowserSlot::Creating { .. } | BrowserSlot::Empty => None,
        }
    }

    /// Drain every tab from the map. Used by `destroy_all_browser_tabs`
    /// from `RunEvent::Exit` and `WindowEvent::Destroyed`. (Drawer-close
    /// no longer drains — the r4 local-lane spec change hides tabs
    /// off-screen instead, preserving state across close→reopen.)
    /// Returns the `Webview<R>` handles the caller must close.
    pub fn take_all_tabs(&self) -> Vec<Webview<R>> {
        let mut out = Vec::new();
        if let Ok(mut tabs) = self.tabs.lock() {
            let drained: Vec<_> = tabs.drain().collect();
            for (_id, slot) in drained {
                if let BrowserSlot::Ready { webview, .. } = slot {
                    out.push(webview);
                }
            }
        }
        if let Ok(mut lb) = self.last_bounds.lock() {
            lb.clear();
        }
        out
    }

    /// Slot-reservation primitive for create. Atomically:
    /// 1. Rejects if the tab's slot is `Creating` OR `Ready` (preserves the
    ///    singleton-reservation guarantee per tab — duplicate Tauri labels
    ///    would crash `add_child`).
    /// 2. On `Empty` (or absent map entry): bumps `generation`, transitions
    ///    to `Creating { gen }`, returns a `CreateGuard` carrying that
    ///    generation and the tab_id.
    pub fn try_reserve_for_create(&self, tab_id: &str) -> Result<CreateGuard<'_, R>, String> {
        use std::sync::atomic::Ordering;
        let mut tabs = self
            .tabs
            .lock()
            .map_err(|e| format!("tabs lock poisoned: {}", e))?;
        match tabs.get(tab_id) {
            Some(BrowserSlot::Ready { .. }) => {
                return Err(format!("browser tab '{}' already exists", tab_id));
            }
            Some(BrowserSlot::Creating { .. }) => {
                return Err(format!("browser tab '{}' already being created", tab_id));
            }
            Some(BrowserSlot::Empty) | None => {}
        }
        let gen = self.generation.fetch_add(1, Ordering::SeqCst) + 1;
        tabs.insert(tab_id.to_string(), BrowserSlot::Creating { generation: gen });
        Ok(CreateGuard {
            state: self,
            tab_id: tab_id.to_string(),
            generation: gen,
            finalized: false,
        })
    }
}

impl<R: Runtime> Default for BrowserTabsState<R> {
    fn default() -> Self {
        Self::new()
    }
}

/// RAII guard returned by `try_reserve_for_create`. Carries the
/// `generation` captured at reservation time so `finalize` can detect
/// cancellation by destroy or by a newer create reservation for the
/// same tab id.
pub struct CreateGuard<'a, R: Runtime> {
    state: &'a BrowserTabsState<R>,
    tab_id: TabId,
    generation: u64,
    finalized: bool,
}

/// Result of `CreateGuard::finalize` — tells the caller whether the new
/// webview was published or whether it was cancelled (in which case the
/// caller must close it to avoid leaking an OS-layer webview).
pub enum FinalizeOutcome<R: Runtime> {
    /// Slot transitioned `Creating(gen) → Ready(gen, webview)`. Webview is
    /// now owned by the slot.
    Published,
    /// Destroy ran during create OR a newer create reservation superseded
    /// this one. Slot is not modified; caller MUST close the webview to
    /// avoid leaking the OS-layer surface.
    Cancelled(Webview<R>),
}

impl<'a, R: Runtime> CreateGuard<'a, R> {
    /// The tab id this guard reserved. Currently unused — the create
    /// command already has `tab_id` from its caller — but kept for
    /// future observability / logging paths.
    #[allow(dead_code)]
    pub fn tab_id(&self) -> &str {
        &self.tab_id
    }

    /// Try to publish `webview` into the slot. Detects cancellation:
    /// - If slot is still `Creating { generation }` matching ours →
    ///   transition to `Ready { generation, webview }`, return Published.
    /// - Otherwise (slot is missing after destroy, or Creating with a newer
    ///   generation, or Ready from a sibling create) → return
    ///   Cancelled(webview). Caller closes it.
    pub fn finalize(mut self, webview: Webview<R>) -> Result<FinalizeOutcome<R>, String> {
        let mut tabs = self
            .state
            .tabs
            .lock()
            .map_err(|e| format!("tabs lock poisoned: {}", e))?;
        let still_ours = matches!(
            tabs.get(&self.tab_id),
            Some(BrowserSlot::Creating { generation }) if *generation == self.generation
        );
        self.finalized = true;
        if still_ours {
            tabs.insert(
                self.tab_id.clone(),
                BrowserSlot::Ready {
                    generation: self.generation,
                    webview,
                },
            );
            Ok(FinalizeOutcome::Published)
        } else {
            // Slot has moved on (destroyed or superseded). Don't store;
            // hand the webview back to the caller for close.
            Ok(FinalizeOutcome::Cancelled(webview))
        }
    }
}

impl<'a, R: Runtime> Drop for CreateGuard<'a, R> {
    fn drop(&mut self) {
        if !self.finalized {
            // Build failed before finalize. Roll back ONLY if the slot
            // still matches our generation — otherwise a newer create
            // reservation has already taken the slot and we mustn't
            // disturb it.
            if let Ok(mut tabs) = self.state.tabs.lock() {
                let still_ours = matches!(
                    tabs.get(&self.tab_id),
                    Some(BrowserSlot::Creating { generation }) if *generation == self.generation
                );
                if still_ours {
                    tabs.remove(&self.tab_id);
                }
            }
        }
    }
}
