use portable_pty::{Child, MasterPty};
use std::collections::HashMap;
use std::io::Write;
use std::sync::Mutex;
use std::thread::JoinHandle;

pub struct PtySession {
    // Drop order matters: child first, then writer, then reader thread (join), then master last.
    // Rust drops fields in declaration order, but we use an explicit Drop impl for safety.
    pub child: Box<dyn Child + Send + Sync>,
    pub writer: Box<dyn Write + Send>,
    pub reader_thread: Option<JoinHandle<()>>,
    pub master: Box<dyn MasterPty + Send>,
}

impl Drop for PtySession {
    fn drop(&mut self) {
        // 1. Kill child process — causes PTY to send EOF/EIO to reader
        let _ = self.child.kill();
        // 2. Drop writer — closes write end of PTY
        // (writer is dropped automatically after this fn, but we want ordering clarity)
        // 3. Join reader thread — wait for it to finish reading before dropping master
        if let Some(handle) = self.reader_thread.take() {
            let _ = handle.join();
        }
        // 4. master drops automatically last (declared last in struct)
    }
}

pub struct AppState {
    pub sessions: Mutex<HashMap<String, PtySession>>,
    /// Cached shell environment — resolved once via login shell, reused for all PTYs.
    /// None = not yet bootstrapped. Some(map) = ready.
    pub cached_env: Mutex<Option<HashMap<String, String>>>,
    /// Serialization lock for settings.json read-modify-write. Both
    /// `set_settings` (full struct) and `set_browser_settings` (partial)
    /// acquire this during their RMW cycle so concurrent writers can't
    /// lose updates. Phase-3 Round-2 3-way convergent fix.
    pub settings_io_lock: Mutex<()>,
}

impl AppState {
    pub fn new() -> Self {
        Self {
            sessions: Mutex::new(HashMap::new()),
            cached_env: Mutex::new(None),
            settings_io_lock: Mutex::new(()),
        }
    }
}

// ---------------------------------------------------------------------------
// Browser-tabs state (browser-tabs cycle — feature/browser-integration)
// ---------------------------------------------------------------------------

use tauri::{LogicalPosition, LogicalSize, Position, Rect as DpiRect, Runtime, Size, Webview};

/// Tab identifier — UUID string generated by the frontend via
/// `crypto.randomUUID()`. Used both as the map key in `BrowserTabsState`
/// and as the suffix of the Tauri webview label (`browser-tab-<uuid>`).
pub type TabId = String;

/// Per-tab webview slot. Mirrors the prior singleton state machine
/// (Empty → Creating → Ready → Empty) but is now stored in a
/// `HashMap<TabId, BrowserSlot<R>>` so every tab has independent
/// lifecycle and CreateGuard generation tracking.
///
/// `Empty` is documented but not currently inserted into the map —
/// destroyed tabs simply remove the entry. Kept for future explicit
/// pre-create reservation flows.
pub enum BrowserSlot<R: Runtime> {
    #[allow(dead_code)]
    Empty,
    Creating {
        generation: u64,
    },
    Ready {
        // Read by the variant-pattern match in `take_tab` / `clone_tab`
        // even though the field itself is destructured with `..`.
        #[allow(dead_code)]
        generation: u64,
        webview: Webview<R>,
    },
}

/// Wire-format rect used at the IPC boundary. Mirrors `src/types/browser.ts::Rect`.
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Rect {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

impl Rect {
    /// Translate the IPC rect into Tauri's logical-pixel rect used by
    /// `Webview::set_bounds`. Tauri 2 handles DPR internally.
    pub fn to_dpi_rect(self) -> DpiRect {
        DpiRect {
            position: Position::Logical(LogicalPosition { x: self.x, y: self.y }),
            size: Size::Logical(LogicalSize {
                width: self.width,
                height: self.height,
            }),
        }
    }
}

/// Browser-drawer Rust-side state. Two `HashMap`-backed mutexes plus a
/// global monotonic generation counter:
/// - `tabs`: per-tab `BrowserSlot` machine (Empty → Creating → Ready → Empty).
/// - `last_bounds`: per-tab Rect dedup cache for `set_browser_tab_bounds`
///   (per-tab — a singleton cache would thrash on every active-tab switch).
/// - `generation`: shared monotonic counter; each tab's `CreateGuard`
///   captures its slot generation independently.
///
/// Lock-order convention: `last_bounds` BEFORE `tabs`. No command currently
/// locks both simultaneously; documented for future regression prevention.
pub struct BrowserTabsState<R: Runtime> {
    pub tabs: Mutex<HashMap<TabId, BrowserSlot<R>>>,
    pub last_bounds: Mutex<HashMap<TabId, Rect>>,
    pub generation: std::sync::atomic::AtomicU64,
}

impl<R: Runtime> BrowserTabsState<R> {
    pub fn new() -> Self {
        Self {
            tabs: Mutex::new(HashMap::new()),
            last_bounds: Mutex::new(HashMap::new()),
            generation: std::sync::atomic::AtomicU64::new(0),
        }
    }

    /// Deterministic webview label from a tab id. Tauri rejects duplicate
    /// webview labels, so we prefix the UUID with `browser-tab-` so the
    /// shape is stable + searchable in logs.
    pub fn label_for(tab_id: &str) -> String {
        format!("browser-tab-{}", tab_id)
    }

    /// Non-destroy primitive: clone the `Webview<R>` handle out of the
    /// slot if it's `Ready`. Used by per-tab nav commands. Leaves the
    /// slot in `Ready`.
    pub fn clone_tab(&self, tab_id: &str) -> Option<Webview<R>> {
        let tabs = self.tabs.lock().ok()?;
        match tabs.get(tab_id)? {
            BrowserSlot::Ready { webview, .. } => Some(webview.clone()),
            _ => None,
        }
    }

    /// Destroy-only primitive: always transition the slot to `Empty`
    /// (removed from the map entirely), regardless of current state.
    /// - `Ready { webview, .. }` → return `Some(webview)`, entry removed.
    /// - `Creating { .. }` → entry removed; in-flight `finalize` with that
    ///   generation will see the mismatch and close-and-discard the
    ///   webview it was about to publish.
    /// - `Empty` / missing → no-op `None`.
    pub fn take_tab(&self, tab_id: &str) -> Option<Webview<R>> {
        let mut tabs = self.tabs.lock().ok()?;
        match tabs.remove(tab_id)? {
            BrowserSlot::Ready { webview, .. } => Some(webview),
            BrowserSlot::Creating { .. } | BrowserSlot::Empty => None,
        }
    }

    /// Drain every tab from the map. Used by `destroy_all_browser_tabs`
    /// from `RunEvent::Exit` and `WindowEvent::Destroyed`. (Drawer-close
    /// no longer drains — the r4 local-lane spec change hides tabs
    /// off-screen instead, preserving state across close→reopen.)
    /// Returns the `Webview<R>` handles the caller must close.
    pub fn take_all_tabs(&self) -> Vec<Webview<R>> {
        let mut out = Vec::new();
        if let Ok(mut tabs) = self.tabs.lock() {
            let drained: Vec<_> = tabs.drain().collect();
            for (_id, slot) in drained {
                if let BrowserSlot::Ready { webview, .. } = slot {
                    out.push(webview);
                }
            }
        }
        if let Ok(mut lb) = self.last_bounds.lock() {
            lb.clear();
        }
        out
    }

    /// Slot-reservation primitive for create. Atomically:
    /// 1. Rejects if the tab's slot is `Creating` OR `Ready` (preserves the
    ///    singleton-reservation guarantee per tab — duplicate Tauri labels
    ///    would crash `add_child`).
    /// 2. On `Empty` (or absent map entry): bumps `generation`, transitions
    ///    to `Creating { gen }`, returns a `CreateGuard` carrying that
    ///    generation and the tab_id.
    pub fn try_reserve_for_create(&self, tab_id: &str) -> Result<CreateGuard<'_, R>, String> {
        use std::sync::atomic::Ordering;
        let mut tabs = self
            .tabs
            .lock()
            .map_err(|e| format!("tabs lock poisoned: {}", e))?;
        match tabs.get(tab_id) {
            Some(BrowserSlot::Ready { .. }) => {
                return Err(format!("browser tab '{}' already exists", tab_id));
            }
            Some(BrowserSlot::Creating { .. }) => {
                return Err(format!("browser tab '{}' already being created", tab_id));
            }
            Some(BrowserSlot::Empty) | None => {}
        }
        let gen = self.generation.fetch_add(1, Ordering::SeqCst) + 1;
        tabs.insert(tab_id.to_string(), BrowserSlot::Creating { generation: gen });
        Ok(CreateGuard {
            state: self,
            tab_id: tab_id.to_string(),
            generation: gen,
            finalized: false,
        })
    }
}

impl<R: Runtime> Default for BrowserTabsState<R> {
    fn default() -> Self {
        Self::new()
    }
}

/// RAII guard returned by `try_reserve_for_create`. Carries the
/// `generation` captured at reservation time so `finalize` can detect
/// cancellation by destroy or by a newer create reservation for the
/// same tab id.
pub struct CreateGuard<'a, R: Runtime> {
    state: &'a BrowserTabsState<R>,
    tab_id: TabId,
    generation: u64,
    finalized: bool,
}

/// Result of `CreateGuard::finalize` — tells the caller whether the new
/// webview was published or whether it was cancelled (in which case the
/// caller must close it to avoid leaking an OS-layer webview).
pub enum FinalizeOutcome<R: Runtime> {
    /// Slot transitioned `Creating(gen) → Ready(gen, webview)`. Webview is
    /// now owned by the slot.
    Published,
    /// Destroy ran during create OR a newer create reservation superseded
    /// this one. Slot is not modified; caller MUST close the webview to
    /// avoid leaking the OS-layer surface.
    Cancelled(Webview<R>),
}

impl<'a, R: Runtime> CreateGuard<'a, R> {
    /// The tab id this guard reserved. Currently unused — the create
    /// command already has `tab_id` from its caller — but kept for
    /// future observability / logging paths.
    #[allow(dead_code)]
    pub fn tab_id(&self) -> &str {
        &self.tab_id
    }

    /// Try to publish `webview` into the slot. Detects cancellation:
    /// - If slot is still `Creating { generation }` matching ours →
    ///   transition to `Ready { generation, webview }`, return Published.
    /// - Otherwise (slot is missing after destroy, or Creating with a newer
    ///   generation, or Ready from a sibling create) → return
    ///   Cancelled(webview). Caller closes it.
    pub fn finalize(mut self, webview: Webview<R>) -> Result<FinalizeOutcome<R>, String> {
        let mut tabs = self
            .state
            .tabs
            .lock()
            .map_err(|e| format!("tabs lock poisoned: {}", e))?;
        let still_ours = matches!(
            tabs.get(&self.tab_id),
            Some(BrowserSlot::Creating { generation }) if *generation == self.generation
        );
        self.finalized = true;
        if still_ours {
            tabs.insert(
                self.tab_id.clone(),
                BrowserSlot::Ready {
                    generation: self.generation,
                    webview,
                },
            );
            Ok(FinalizeOutcome::Published)
        } else {
            // Slot has moved on (destroyed or superseded). Don't store;
            // hand the webview back to the caller for close.
            Ok(FinalizeOutcome::Cancelled(webview))
        }
    }
}

impl<'a, R: Runtime> Drop for CreateGuard<'a, R> {
    fn drop(&mut self) {
        if !self.finalized {
            // Build failed before finalize. Roll back ONLY if the slot
            // still matches our generation — otherwise a newer create
            // reservation has already taken the slot and we mustn't
            // disturb it.
            if let Ok(mut tabs) = self.state.tabs.lock() {
                let still_ours = matches!(
                    tabs.get(&self.tab_id),
                    Some(BrowserSlot::Creating { generation }) if *generation == self.generation
                );
                if still_ours {
                    tabs.remove(&self.tab_id);
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// LocalFileTokenRegistry (browser-localfile cycle — feat/browser-integration)
//
// Phase-5 skeleton (codebase-planner system lane). Defines the public
// contract for the `localfile://localhost/<token>` URI scheme's token-binding
// registry. Method bodies are `todo!()` placeholders; the downstream
// codebase-implementer fills them in under the
// (interfaces only, human-confirmed) marker.
//
// See `commands::localfile` for the orchestrating Tauri command,
// protocol handler, and private helpers (validate_picked_path,
// classify_mime, build_localfile_response, validate_localfile_url_shape).
// Token generation is intentionally NOT a separate helper — it
// happens inside `LocalFileTokenStore::mint` under the same lock
// scope as the insert (TOCTOU-safe).
// ---------------------------------------------------------------------------

use std::path::PathBuf;
use std::time::Instant;

/// URL-safe-base64-encoded 128-bit random token. Strict shape:
/// `^[A-Za-z0-9_-]{22}$`. Used at the IPC boundary, in the URI
/// path, and as the registry map key.
pub type Token = String;

/// Per-token entry stored by `LocalFileTokenRegistry`.
///
/// Tab-scoping invariant: `tab_id` is the tab that MINTED this
/// token. The protocol handler enforces that any incoming request
/// bearing this token originated from the same tab — by reading
/// `UriSchemeContext::webview_label()`, stripping the
/// `browser-tab-` prefix produced by `BrowserTabsState::label_for`,
/// and comparing against this field.
#[derive(Debug, Clone)]
pub struct TokenEntry {
    pub tab_id: TabId,
    pub canonical_path: PathBuf,
    pub mime: String,
    /// Wall-clock instant the token was minted. v1 has no TTL (plan C6
    /// — tab-lifetime scoping is sufficient), so this is set by `mint`
    /// but not yet read. Kept on the struct for future TTL,
    /// instrumentation, or diagnostic dumps. Don't remove without
    /// closing the C6 deferral.
    #[allow(dead_code)]
    pub minted_at: Instant,
}

/// Errors returned by `LocalFileTokenStore::mint`. Read-only and
/// best-effort methods (`lookup`, `revoke_for_tab`, `clear`) are
/// total over their inputs by design — their Mutex-poisoning case
/// is swallowed and surfaced as `None` / `0` to keep the security
/// default safe (404 on uncertainty; best-effort cleanup over leak).
#[derive(Debug)]
pub enum RegistryError {
    /// Mutex poisoned by a panic on a prior call holding the lock.
    /// Not retryable. Caller bubbles the failure to the user; the
    /// app is in a degraded state that requires restart.
    LockPoisoned,
    /// Collision-budget exhausted after N rerolls. Astronomically
    /// improbable with 128-bit tokens; signals a broken RNG path
    /// (e.g. getrandom failing silently).
    TokenSpaceExhausted,
}

/// Registry contract for the `localfile://` URI scheme.
///
/// Cohesion source: all methods operate on the same private
/// `HashMap<Token, TokenEntry>` guarded by a single Mutex; same
/// failure domain (lock poisoning); shared lifecycle (app process
/// lifetime).
///
/// Lock-order convention: this Mutex is independent of
/// `BrowserTabsState`'s `tabs` and `last_bounds` mutexes. No code
/// path currently locks both this Mutex AND any `BrowserTabsState`
/// Mutex simultaneously. If a future code path needs to, the
/// convention is `LocalFileTokenRegistry` AFTER `BrowserTabsState`
/// locks (i.e. last_bounds -> tabs -> registry).
pub trait LocalFileTokenStore: Send + Sync {
    /// Atomically mint a fresh token, bind it to the supplied tab +
    /// canonical path + MIME, store the entry in the registry, and
    /// return the token to the caller.
    ///
    /// **Responsibility:** Atomically mint a fresh token, bind it
    /// to the supplied tab + canonical path + MIME, store the entry
    /// in the registry, and return the token to the caller.
    /// **Pipeline-position:** `commands::localfile::classify_mime`
    /// -> THIS -> Tauri command boundary (returned to the frontend).
    /// Token generation (16 bytes `getrandom` -> URL-safe-base64
    /// + collision check against `self.entries`) happens INSIDE
    /// `mint`'s impl under the same lock scope as the insert.
    /// **Inputs:**
    /// - `tab_id`: `TabId` — UUID-shaped string of the tab that owns
    ///   this picked file; the protocol handler enforces that only
    ///   requests originating from this tab can be served.
    /// - `canonical_path`: `PathBuf` — already canonicalized AND
    ///   already validated (regular file, not under deny-prefix);
    ///   `mint` does NOT re-validate, by design.
    /// - `mime`: `String` — MIME type for the response Content-Type
    ///   header; precomputed by the caller via `classify_mime`; must
    ///   contain no CR/LF/control bytes.
    /// **Outputs:** `Token` — 22-char URL-safe-base64 string;
    /// unique across the live registry at the moment of return.
    /// **Side-effects:** mutates the registry's internal HashMap;
    /// holds the internal Mutex for the duration of the
    /// generate-and-insert (both happen under the SAME lock scope
    /// to close the freshness-vs-insert TOCTOU window); consumes
    /// 16 bytes of `getrandom` entropy per generation attempt. No
    /// I/O; no time; no network.
    /// **Preconditions:** `canonical_path` exists, is a regular file
    /// (not a directory, symlink, socket, FIFO, or device), and is
    /// not under any entry in the deny-prefix list. `mime` is a
    /// syntactically valid MIME string. These invariants are
    /// established by `commands::localfile::validate_picked_path`
    /// and `classify_mime` and trusted here.
    /// **Postconditions:** the registry contains exactly one new
    /// `TokenEntry` keyed by the returned `Token`; that entry's
    /// `tab_id` equals the supplied `tab_id`; `minted_at` is set to
    /// `Instant::now()` at insert time. Each call produces a fresh
    /// token even with identical inputs — re-picking the same file
    /// twice yields two independent tokens (deliberate).
    /// **Failure-modes:**
    /// - `RegistryError::LockPoisoned` — internal Mutex poisoned by
    ///   a prior panic; not retryable.
    /// - `RegistryError::TokenSpaceExhausted` — random-token
    ///   generation collided too many times in a row (default
    ///   threshold: 32 rerolls); signals a broken RNG.
    /// **Collaborators:** None at the interface level. Token
    /// generation (16 bytes `getrandom` -> URL-safe-base64 ->
    /// collision check) is an internal concern of this trait's impl
    /// and happens under the same lock scope as the insert, so it
    /// is not surfaced as a separate collaborator.
    fn mint(
        &self,
        tab_id: TabId,
        canonical_path: PathBuf,
        mime: String,
    ) -> Result<Token, RegistryError>;

    /// Look up a token, verify it belongs to the requesting tab,
    /// return a clone of the entry on success.
    ///
    /// **Responsibility:** Atomically retrieve the `TokenEntry` for
    /// `token`, verify `entry.tab_id == owning_tab_id`, return a
    /// clone on hit. Return `None` on miss OR tab-mismatch — caller
    /// cannot distinguish the two by design (deliberate
    /// information-leak prevention).
    /// **Pipeline-position:** `localfile_protocol_handler` (parsing
    /// the URL and `UriSchemeContext::webview_label`) -> THIS ->
    /// caller decides 200 (proceed to read+respond) vs 404.
    /// **Inputs:**
    /// - `token`: `&str` — caller-supplied; expected shape is the
    ///   22-char base64-url alphabet, but `lookup` does NOT validate
    ///   shape (cheap; HashMap miss handles malformed input).
    /// - `owning_tab_id`: `&str` — tab_id extracted from
    ///   `UriSchemeContext::webview_label`. Caller has already
    ///   stripped the `browser-tab-` prefix.
    /// **Outputs:** `Option<TokenEntry>` — `Some(clone)` on hit AND
    /// tab match; `None` on miss OR tab mismatch OR (swallowed)
    /// lock poison.
    /// **Side-effects:** holds the internal Mutex briefly for read
    /// + clone. No I/O; no mutation of the registry contents.
    /// **Preconditions:** None. (`token` and `owning_tab_id` may be
    /// any string slice; registry handles miss gracefully.)
    /// **Postconditions:** the registry is unchanged. Read-only,
    /// idempotent.
    /// **Failure-modes:** None at the signature level. Mutex
    /// poisoning is swallowed and surfaced as `None`, because the
    /// protocol handler treats a poisoned mutex the same as a miss
    /// (refuse to serve over leaking a stale token).
    /// **Collaborators:** None. (terminal lookup against the local
    /// HashMap.)
    fn lookup(&self, token: &str, owning_tab_id: &str) -> Option<TokenEntry>;

    /// Drop every token whose `tab_id` matches the supplied id.
    ///
    /// **Responsibility:** Remove every registry entry whose
    /// `tab_id` equals the supplied id. Used by browser-tab destroy
    /// and navigate-away hooks to bound a token's lifetime to its
    /// tab's lifetime.
    /// **Pipeline-position:**
    /// `commands::browser::destroy_browser_tab_impl` OR
    /// `commands::browser::navigate_browser_tab` (when destination
    /// is NOT a `localfile://` URL) -> THIS.
    /// **Inputs:**
    /// - `tab_id`: `&str` — id of the tab being destroyed or
    ///   navigating away from a localfile URL.
    /// **Outputs:** `usize` — count of entries removed; zero is a
    /// valid result (no localfile tokens were minted in this tab).
    /// **Side-effects:** mutates the internal HashMap by removing
    /// matching entries; holds the Mutex for the duration of the
    /// scan-and-remove pass.
    /// **Preconditions:** None.
    /// **Postconditions:** the registry contains no entry whose
    /// `tab_id` equals the supplied `tab_id`. Other entries are
    /// unchanged. Idempotent: repeated calls with the same id
    /// return 0 after the first.
    /// **Failure-modes:** None at the signature level. Mutex
    /// poisoning swallowed and surfaced as 0 — best-effort
    /// revocation beats panicking, because the alternative is
    /// leaking tokens past their tab's lifetime.
    /// **Collaborators:** None.
    fn revoke_for_tab(&self, tab_id: &str) -> usize;

    /// Drop every entry in the registry.
    ///
    /// **Responsibility:** Atomically remove every entry. Used at
    /// app teardown so no stale token-to-path mappings survive
    /// process restart (defense-in-depth — the registry is
    /// in-memory only, so process-restart already loses them).
    /// **Pipeline-position:**
    /// `commands::browser::destroy_all_browser_tabs_impl` OR
    /// `lib.rs::run()` `WindowEvent::Destroyed` / `RunEvent::Exit`
    /// hooks -> THIS.
    /// **Inputs:** None.
    /// **Outputs:** `usize` — count of entries dropped; zero is a
    /// valid result.
    /// **Side-effects:** mutates the internal HashMap (drains all
    /// entries); holds the Mutex for the duration of the drain.
    /// **Preconditions:** None.
    /// **Postconditions:** the registry is empty after return.
    /// Idempotent.
    /// **Failure-modes:** None at the signature level. Mutex
    /// poisoning swallowed for the same reason as `revoke_for_tab`.
    /// **Collaborators:** None.
    fn clear(&self) -> usize;
}

/// Concrete implementation of `LocalFileTokenStore`. Internal
/// layout: `Mutex<HashMap<Token, TokenEntry>>`. Single source of
/// truth for the registry's contents; no shadow state, no caching,
/// no TTL. Created once in `lib.rs::run()` and `.manage()`'d.
pub struct LocalFileTokenRegistry {
    pub entries: Mutex<HashMap<Token, TokenEntry>>,
}

impl LocalFileTokenRegistry {
    /// Construct an empty registry.
    ///
    /// **Responsibility:** Initialize a fresh, empty registry.
    /// Called once in `lib.rs::run()` before `.manage()`.
    /// **Pipeline-position:** `lib.rs::run()` -> THIS -> registry
    /// is `.manage()`'d on the Tauri builder and from then on lives
    /// inside the app's typemap until process exit.
    /// **Inputs:** None.
    /// **Outputs:** `Self` — empty registry; `entries.lock()` would
    /// observe an empty HashMap.
    /// **Side-effects:** None. (no I/O; one empty HashMap allocation.)
    /// **Preconditions:** None.
    /// **Postconditions:** the returned registry contains zero
    /// entries; the internal Mutex is unlocked.
    /// **Failure-modes:** None. (total over its (empty) inputs.)
    /// **Collaborators:** None.
    pub fn new() -> Self {
        Self {
            entries: Mutex::new(HashMap::new()),
        }
    }
}

impl Default for LocalFileTokenRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl LocalFileTokenStore for LocalFileTokenRegistry {
    fn mint(
        &self,
        tab_id: TabId,
        canonical_path: PathBuf,
        mime: String,
    ) -> Result<Token, RegistryError> {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
        use rand::RngCore;

        let mut entries = self
            .entries
            .lock()
            .map_err(|_| RegistryError::LockPoisoned)?;

        // Token generation under-lock: 16 bytes from OsRng -> URL-safe-base64
        // (no padding, yielding exactly 22 chars) -> collision check against
        // current keys. Retry cap of 32 — a working OsRng cannot collide twice
        // in a row, so anything past 32 signals broken entropy and we surface
        // TokenSpaceExhausted instead of looping forever.
        let mut buf = [0u8; 16];
        for _ in 0..32 {
            rand::rngs::OsRng.fill_bytes(&mut buf);
            let token = URL_SAFE_NO_PAD.encode(buf);
            if !entries.contains_key(&token) {
                entries.insert(
                    token.clone(),
                    TokenEntry {
                        tab_id,
                        canonical_path,
                        mime,
                        minted_at: Instant::now(),
                    },
                );
                return Ok(token);
            }
        }
        Err(RegistryError::TokenSpaceExhausted)
    }

    fn lookup(&self, token: &str, owning_tab_id: &str) -> Option<TokenEntry> {
        let entries = self.entries.lock().ok()?;
        let entry = entries.get(token)?;
        if entry.tab_id != owning_tab_id {
            return None;
        }
        Some(entry.clone())
    }

    fn revoke_for_tab(&self, tab_id: &str) -> usize {
        match self.entries.lock() {
            Ok(mut entries) => {
                let before = entries.len();
                entries.retain(|_, entry| entry.tab_id != tab_id);
                before - entries.len()
            }
            Err(_) => 0,
        }
    }

    fn clear(&self) -> usize {
        match self.entries.lock() {
            Ok(mut entries) => {
                let n = entries.len();
                entries.clear();
                n
            }
            Err(_) => 0,
        }
    }
}
